spring.datasource.url=jdbc:derby:db/ZZL
spring.datasource.username=ZARZADZANIE_CZASEM_PRACOWNIKA
spring.datasource.password=root
spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
spring.jpa.database-platform=org.hibernate.community.dialect.DerbyDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Serializuj typy java.time jako ciągi ISO-8601 (np. "2024-01-31"), a nie tablice.
spring.jackson.serialization.write-dates-as-timestamps=false
