CREATE SCHEMA ZARZADZANIE_CZASEM_PRACOWNIKA;

CREATE TABLE ZARZADZANIE_CZASEM_PRACOWNIKA.STANOWISKO
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAZWA VARCHAR(200) NOT NULL,
VERSION INT DEFAULT 0,
CONSTRAINT STANOWISKO_PK PRIMARY KEY (ID)
);


CREATE TABLE ZARZADZANIE_CZASEM_PRACOWNIKA.DZIAL
(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAZWA VARCHAR(100) not null,
OPIS VARCHAR(5000),
VERSION INT DEFAULT 0,
CONSTRAINT DZIAL_PK PRIMARY KEY (ID)
);

CREATE TABLE ZARZADZANIE_CZASEM_PRACOWNIKA.PRACOWNIK
(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
IMIE VARCHAR(100) not null,
NAZWISKO VARCHAR(200) not null,
PESEL VARCHAR(11),
STANOWISKO INT,
DZIAL INT,
VERSION INT DEFAULT 0,
CONSTRAINT STANOWISKO_FK FOREIGN KEY (STANOWISKO) REFERENCES ZARZADZANIE_CZASEM_PRACOWNIKA.STANOWISKO (ID),
CONSTRAINT DZIAL_FK FOREIGN KEY (DZIAL) REFERENCES ZARZADZANIE_CZASEM_PRACOWNIKA.DZIAL (ID),
CONSTRAINT PRACOWNIK_PK PRIMARY KEY (ID)
);

CREATE TABLE ZARZADZANIE_CZASEM_PRACOWNIKA.SLOWNIK
(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
SLOWNIK VARCHAR(100) not null,
WARTOSC VARCHAR(200) not null,
VERSION INT DEFAULT 0,
CONSTRAINT SLOWNIK_PK PRIMARY KEY (ID)
);


CREATE TABLE ZARZADZANIE_CZASEM_PRACOWNIKA.KALENDARZ
(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
DATA DATE not null,
TYP INT,
PRACOWNIK INT,
VERSION INT DEFAULT 0,
CONSTRAINT TYP_FK FOREIGN KEY (TYP) REFERENCES ZARZADZANIE_CZASEM_PRACOWNIKA.SLOWNIK (ID),
CONSTRAINT PRACOWNIK_FK FOREIGN KEY (PRACOWNIK) REFERENCES ZARZADZANIE_CZASEM_PRACOWNIKA.PRACOWNIK (ID),
CONSTRAINT KALENDARZ_PK PRIMARY KEY (ID)
);

CREATE TABLE ZARZADZANIE_CZASEM_PRACOWNIKA.PROJEKT
(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TYTUL VARCHAR(100) not null,
OPIS VARCHAR(20000),
DATA_ROZPOCZECIA DATE,
DATA_ZAKONCZENIA DATE,
DZIAL INT,
VERSION INT DEFAULT 0,
CONSTRAINT DZIAL_PROJEKTU_FK FOREIGN KEY (DZIAL) REFERENCES ZARZADZANIE_CZASEM_PRACOWNIKA.DZIAL (ID),
CONSTRAINT DATA_ZAKONCZENIA_CHCK CHECK (DATA_ZAKONCZENIA > DATA_ROZPOCZECIA),
CONSTRAINT PROJEKT_PK PRIMARY KEY (ID)
);

CREATE TABLE ZARZADZANIE_CZASEM_PRACOWNIKA.PUNKT_KLUCZOWY
(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAZWA VARCHAR(100) not null,
OPIS VARCHAR(20000),
DATA_UTWORZENIA DATE,
DATA_ZAKONCZENIA DATE,
PRIORYTET INT,
PROJEKT INT,
VERSION INT DEFAULT 0,
CONSTRAINT PROJEKT_FK FOREIGN KEY (PROJEKT) REFERENCES ZARZADZANIE_CZASEM_PRACOWNIKA.PROJEKT (ID),
CONSTRAINT DATA_ZAKONCZENIA_PUNKTU_CHCK CHECK (DATA_ZAKONCZENIA > DATA_UTWORZENIA),
CONSTRAINT PUNKT_KLUCZOWY_PK PRIMARY KEY (ID)
);

CREATE TABLE ZARZADZANIE_CZASEM_PRACOWNIKA.EWIDENCJA
(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
DATA_WEJSCIA DATE,
DATA_WYJSCIA DATE,
PRACOWNIK INT,
VERSION INT DEFAULT 0,
CONSTRAINT PRACOWNIK_EWIDENCJA_FK FOREIGN KEY (PRACOWNIK) REFERENCES ZARZADZANIE_CZASEM_PRACOWNIKA.PRACOWNIK (ID),
CONSTRAINT DATA_WYJSCIA_CHCK CHECK (DATA_WYJSCIA > DATA_WEJSCIA),
CONSTRAINT EWIDENCJA_PK PRIMARY KEY (ID)
);




